

name: Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          npm ci
          make lint
        
      - name: build
        run: make build
